# Generated by Django 5.2.16 on 2026-07-25 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField()),
                ('theme', models.CharField(blank=True, max_length=120)),
                ('date', models.DateField()),
                ('time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(max_length=160)),
                ('address', models.CharField(blank=True, max_length=240)),
                ('dress_code', models.CharField(blank=True, max_length=160)),
                ('program', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['date', 'time'],
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('location', models.CharField(max_length=160)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('partnership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='students.partnership')),
            ],
            options={
                'ordering': ['date', 'time'],
            },
        ),
    ]
