# Generated by Django 5.2.16 on 2026-07-25 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='hero_image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='preparation_tips',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='rules',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='events.event')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
