# Generated by Django 5.2.16 on 2026-07-25 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(blank=True, max_length=8)),
                ('class_letter', models.CharField(blank=True, max_length=4)),
                ('height', models.PositiveSmallIntegerField(blank=True, help_text='Height in cm', null=True)),
                ('bio', models.TextField(blank=True, max_length=600)),
                ('dance_experience', models.CharField(blank=True, max_length=40)),
                ('personality', models.CharField(blank=True, max_length=80)),
                ('preferred_rehearsal_time', models.CharField(blank=True, max_length=80)),
                ('photo', models.ImageField(blank=True, upload_to='profiles/')),
                ('agreed_to_rules', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Needs changes')], default='pending', max_length=10)),
                ('moderation_note', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Partnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partnerships_one', to=settings.AUTH_USER_MODEL)),
                ('student_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partnerships_two', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('student_one', 'student_two'), name='unique_partnership')],
            },
        ),
        migrations.CreateModel(
            name='PartnershipRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_partnership_requests', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_partnership_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('sender', 'receiver'), name='unique_partnership_request')],
            },
        ),
    ]
