# Generated by Django 5.2.16 on 2026-07-25 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_partnership_preparation_complete_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalPartnerProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Awaiting response'), ('accepted', 'Final partnership confirmed'), ('declined', 'Declined')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Rehearsal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=160)),
                ('note', models.CharField(blank=True, max_length=280)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['date', 'time', '-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='partnershiprequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveConstraint(
            model_name='partnershiprequest',
            name='unique_partnership_request',
        ),
        migrations.AddField(
            model_name='partnershiprequest',
            name='location',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='partnershiprequest',
            name='note',
            field=models.CharField(blank=True, max_length=280),
        ),
        migrations.AddField(
            model_name='partnershiprequest',
            name='proposed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partnershiprequest',
            name='proposed_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='finalpartnerproposal',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_partner_proposals_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='finalpartnerproposal',
            name='proposer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_partner_proposals_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rehearsal',
            name='student_one',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rehearsals_one', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rehearsal',
            name='student_two',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rehearsals_two', to=settings.AUTH_USER_MODEL),
        ),
    ]
