# Generated by Django 5.2.16 on 2026-07-25 20:36

from django.db import migrations, models


def set_demo_genders(apps, schema_editor):
    Profile = apps.get_model('students', 'Profile')
    male_names = {'Noah', 'Ethan', 'Lucas', 'Leo', 'Daniel', 'Max', 'Ryan', 'Ben', 'Alex', 'Sam'}
    female_names = {'Amelia', 'Sofia', 'Olivia', 'Maya', 'Emma', 'Grace', 'Lily', 'Ella', 'Chloe', 'Ava', 'Мария'}
    for profile in Profile.objects.select_related('user'):
        if profile.user.first_name in male_names:
            profile.gender = 'male'
        elif profile.user.first_name in female_names:
            profile.gender = 'female'
        else:
            continue
        profile.save(update_fields=['gender'])


def clear_demo_genders(apps, schema_editor):
    Profile = apps.get_model('students', 'Profile')
    Profile.objects.update(gender='')


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_finalpartnerproposal_rehearsal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('female', 'Female'), ('male', 'Male')], max_length=10),
        ),
        migrations.RunPython(set_demo_genders, clear_demo_genders),
    ]
