# Generated by Django 5.2.16 on 2026-07-25 19:37

from django.db import migrations, models


def simplify_roles(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    InvitationCode = apps.get_model('accounts', 'InvitationCode')
    User.objects.exclude(role='admin').update(role='user')
    User.objects.filter(is_superuser=True).update(role='admin')
    InvitationCode.objects.exclude(role='admin').update(role='user')


def restore_old_roles(apps, schema_editor):
    # The old role cannot be inferred after simplifying it, so all users remain students on reverse.
    User = apps.get_model('accounts', 'User')
    InvitationCode = apps.get_model('accounts', 'InvitationCode')
    User.objects.filter(role='user').update(role='student')
    InvitationCode.objects.filter(role='user').update(role='student')


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(simplify_roles, restore_old_roles),
        migrations.AlterField(
            model_name='invitationcode',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Administrator')], default='user', max_length=12),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Administrator')], default='user', max_length=12),
        ),
    ]
