# Generated by Django 5.2.16 on 2026-07-25 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField(unique=True)),
                ('excerpt', models.TextField()),
                ('body', models.TextField()),
                ('published_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
