# Generated by Django 5.2.16 on 2026-07-25 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-published_at']},
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.CharField(default='Dream Ball Team', max_length=120),
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(default='Student life', max_length=80),
        ),
        migrations.AddField(
            model_name='article',
            name='cover_image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='article',
            name='reading_time',
            field=models.PositiveSmallIntegerField(default=4, help_text='Estimated reading time in minutes'),
        ),
    ]
