# Generated by Django 5.2.16 on 2026-07-25 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='moderator_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('reviewing', 'In review'), ('resolved', 'Resolved')], default='open', max_length=12),
        ),
        migrations.AlterField(
            model_name='report',
            name='reason',
            field=models.CharField(choices=[('spam', 'Spam'), ('photo', 'Inappropriate photo'), ('harassment', 'Harassment'), ('fake', 'Fake profile'), ('other', 'Other')], max_length=16),
        ),
    ]
